// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/SetWheelOffSets.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	rotatJoystick = new Joystick(2);
	
	transJoystick = new Joystick(1);
	
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("SetWheelOffSets", new SetWheelOffSets());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getRotatJoystick() {
	return rotatJoystick;
}

Joystick* OI::getTransJoystick() {
	return transJoystick;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
double OI::getScaledJoystickRadians() {
	double pi = 3.14159;
	double scaledRadians = pi/2;
	double scalingFactor = 1;
	double steerAngle = pi/2;
	double bottomScaling = 1.5;
	double topScaling = 1.75;


	steerAngle = transJoystick->GetDirectionRadians();
	if(steerAngle > pi)
		steerAngle = pi;
	if(steerAngle < -pi)
		steerAngle = -pi;

	if(steerAngle < -pi/2)
		steerAngle = -pi/2 - steerAngle;
	else if(steerAngle < pi/2)
		steerAngle = pi/2 + steerAngle;
	else
		steerAngle = 3*pi/2 - steerAngle;
//	scalingFactor = driverJoystick->GetTwist()/2+1.5;

	scalingFactor = bottomScaling + transJoystick->GetMagnitude()*(topScaling - bottomScaling);
	if (getTransJoystick()->GetMagnitude() < .2)
		scaledRadians = pi/2;
	else
	{
		if(steerAngle <= pi/2)
			scaledRadians = (-(pi/2)/pow(pow(-pi/2,2),scalingFactor/2))*pow(pow(steerAngle-pi/2,2),scalingFactor/2) + pi/2;
		else //if(steerAngle <= pi)
			scaledRadians = ((pi/2)/pow((pi/2),scalingFactor))*pow(steerAngle-pi/2,scalingFactor) + pi/2;
	}
	return scaledRadians;
}

double OI::getJoystickMagnitude() {
	if(getTransJoystick()->GetMagnitude() < .1)
		return 0;
	else
		if (getTransJoystick()->GetY()<0)
			return -getTransJoystick()->GetMagnitude();
		else
			return getTransJoystick()->GetMagnitude();
}
//double OI::getJoystickTwist() {
//	if(fabs(getRotatJoystick()->GetY()) < .1)
//			return 0;
//	else
//		return getRotatJoystick()->GetY()/2;
//}

double OI::getRotatJoystickY() {
	if (fabs(getRotatJoystick()->GetY()) < .1)
		return 0;
	else
		return getRotatJoystick()->GetY();
}

double OI::getJoystickX() {
	if (fabs(getTransJoystick()->GetX()) < .1)
		return 0;
	else
		return getTransJoystick()->GetX();
}
double OI::getJoystickY() {
	if (fabs(getTransJoystick()->GetY()) < .1)
		return 0;
	else
		return getTransJoystick()->GetY();
}
